# -*- coding: utf-8 -*-
"""HW6 PDE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN02oYS25mA2FyYFr2i_BxSpqDLQoUrD

В данном задании вам будет предложено найти стоимость опциона с помощью численного решения уравнения Блэка-Шоулза.

1. Реализуйте явную схему для решения уравнения Блэка-Шоулза для европейского пут-опциона. (5 баллов)
2. Убедитесь, что явная схема условно устойчивая: (5 баллов)
    * проведите расчёты при $h < 0.5 \sigma \sqrt{\tau}, h \geq \sigma \sqrt{\tau}$,
    * изобразите на одном графике решения с разными значениями шага $h$ и аналитическое решение (всего 3 кривые)
3. Реализуйте неявную схему/схему Кранка-Николсона для европейского пут-опциона. (10 баллов)
4. Убедитесь, что построенная схема безусловно устойчива аналогично пункту 2. (10 баллов)
5. Реализуйте любую схему на выбор для американского пут-опциона. (5 баллов)
6. Убедитесь, что цена американского опциона ограничена снизу ценой европейского пут-опциона и функцией выплаты (5 баллов)

Пусть $V^{Am}(t, S)$ -- стоимость европейского пут-опциона, при условии, что мы не исполнили его до момента $t$ включительно.
Тогда на плоскости $(t, S)$ можно выделить две области: область, в которой оптимально гасить опцион
$$
    \text{Expirate} = \{(t, S) : V^{Am}(t, S) = (K - S)\}
$$
и область, в которой оптимально держать опцион:
$$
    \text{Hold} = \{(t, S) : V^{Am}(t, S) > (K - S)\}
$$Граница между этими областями является кривая $B(t)$ -- граница экспирации. В силу монотонности можно определить $B(t)$ следующим образом:
$$
    B(t) = \sup_{S}\{(V^{Am}(t, S) = (K-S)\}
$$

7. \* Постройте границу экспирации $B(t)$ для американского пут-опциона (10 баллов)

## Параметры модели и опциона
"""

import numpy as np
spot_price = 1.0
sigma = 0.2
interest_rate = 0.00

maturity = 1.0
strike = spot_price * np.exp(interest_rate * maturity)

"""## Параметры сеток выбираются исходя из условий заданий. В качестве значений по умолчаню можно брать:"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy.sparse import diags
from scipy.sparse.linalg import spsolve
from scipy.interpolate import interp1d
from scipy.signal import savgol_filter

K = 100
T = 1.0
r = 0.05
sigma = 0.2
S_max = 200

M = 200
N = 500



def black_scholes_put(S, K, T, r, sigma, t=0):
    if T == t:
        return np.maximum(K - S, 0)

    tau = T - t
    d1 = (np.log(S/K) + (r + 0.5*sigma**2)*tau) / (sigma*np.sqrt(tau))
    d2 = d1 - sigma*np.sqrt(tau)

    return K*np.exp(-r*tau)*norm.cdf(-d2) - S*norm.cdf(-d1)

def payoff_put(S, K):
    return np.maximum(K - S, 0)

def explicit_scheme(K, T, r, sigma, S_max, M, N, condition='stable'):
    S_min = 0.1
    S = np.linspace(S_min, S_max, M+1)
    dt = T / N

    #Начальное условие
    V = np.zeros((M+1, N+1))
    V[:, -1] = payoff_put(S, K)

    #Коэффициенты
    dx = (S_max - S_min) / M
    a = 0.5 * dt * sigma**2 * S**2 / dx**2
    b = dt * r * S / (2 * dx)
    c = dt * r

    #Подбор шага по времени для условия устойчивости
    if condition == 'stable':
        dt_stable = 0.4 * dx**2 / (sigma**2 * S_max**2)
        if dt > dt_stable:
            dt = dt_stable
            N = int(T / dt) + 1
            V = np.zeros((M+1, N+1))
            V[:, -1] = payoff_put(S, K)

    for n in range(N, 0, -1):
        for i in range(1, M):
            V[i, n-1] = V[i, n] + a[i] * (V[i+1, n] - 2*V[i, n] + V[i-1, n]) \
                        + b[i] * (V[i+1, n] - V[i-1, n]) - c * V[i, n]

        #Граничные условия
        V[0, n-1] = K * np.exp(-r * (T - (n-1)*dt))  #При S=0
        V[M, n-1] = 0  #При S --> inf

    time_grid = np.linspace(0, T, N+1)
    return S, V, time_grid

def crank_nicolson_scheme(K, T, r, sigma, S_max, M, N):
    S_min = 0.1
    S = np.linspace(S_min, S_max, M+1)
    dt = T / N
    dx = (S_max - S_min) / M

    #Начальное условие
    V = np.zeros((M+1, N+1))
    V[:, -1] = payoff_put(S, K)

    alpha = 0.25 * dt * (sigma**2) * (S[1:-1]**2) / (dx**2)
    beta = 0.25 * dt * r * S[1:-1] / dx
    gamma = 0.5 * dt * r

    main_diag_A = np.ones(M+1)
    main_diag_A[1:-1] = 1 + 2*alpha + gamma

    lower_diag_A = np.zeros(M)
    lower_diag_A[1:] = -alpha + beta

    upper_diag_A = np.zeros(M)
    upper_diag_A[:-1] = -alpha - beta

    main_diag_B = np.ones(M+1)
    main_diag_B[1:-1] = 1 - 2*alpha - gamma

    lower_diag_B = np.zeros(M)
    lower_diag_B[1:] = alpha - beta

    upper_diag_B = np.zeros(M)
    upper_diag_B[:-1] = alpha + beta

    main_diag_A[0] = 1
    upper_diag_A[0] = 0
    lower_diag_A[0] = 0

    # При S=S_max: V = 0
    main_diag_A[-1] = 1
    lower_diag_A[-1] = 0
    upper_diag_A[-1] = 0

    main_diag_B[0] = 1
    upper_diag_B[0] = 0
    lower_diag_B[0] = 0

    main_diag_B[-1] = 1
    lower_diag_B[-1] = 0
    upper_diag_B[-1] = 0

    # Создание матриц
    A = diags([lower_diag_A, main_diag_A, upper_diag_A], [-1, 0, 1], format='csr')
    B = diags([lower_diag_B, main_diag_B, upper_diag_B], [-1, 0, 1], format='csr')

    #Обратный ход
    for n in range(N, 0, -1):
        rhs = B.dot(V[:, n])

        t_prev = (n-1) * dt
        rhs[0] = K * np.exp(-r * (T - t_prev))
        rhs[-1] = 0

        #Решение системы
        V[:, n-1] = spsolve(A, rhs)

    time_grid = np.linspace(0, T, N+1)

    # Проверка результата
    bs_price = black_scholes_put(100, K, T, r, sigma)
    cn_price = np.interp(100, S, V[:, 0])
    print(f"Проверка точности: BS цена при S=100: {bs_price:.4f}, CN цена: {cn_price:.4f}, "
          f"Ошибка: {abs(bs_price-cn_price):.6f}")

    return S, V, time_grid

#Применение схемы Кранка-Николсон в американскому пут-опциону
def american_put_scheme(K, T, r, sigma, S_max, M, N):
    S_min = 0.1
    S = np.linspace(S_min, S_max, M+1)
    dt = T / N
    dx = (S_max - S_min) / M

    # Начальное условие
    V = np.zeros((M+1, N+1))
    V[:, -1] = payoff_put(S, K)

    # Коэффициенты для внутренних точек (i=1..M-1)
    alpha = 0.25 * dt * sigma**2 * S[1:-1]**2 / (dx**2)
    beta = 0.25 * dt * r * S[1:-1] / dx
    gamma = 0.5 * dt * r

    #левая часть
    main_diag_A = np.ones(M+1)
    main_diag_A[1:-1] = 1 + 2*alpha + gamma

    lower_diag_A = np.zeros(M)
    lower_diag_A[1:] = -alpha + beta

    upper_diag_A = np.zeros(M)
    upper_diag_A[:-1] = -alpha - beta

    #правая часть
    main_diag_B = np.ones(M+1)
    main_diag_B[1:-1] = 1 - 2*alpha - gamma

    lower_diag_B = np.zeros(M)
    lower_diag_B[1:] = alpha - beta

    upper_diag_B = np.zeros(M)
    upper_diag_B[:-1] = alpha + beta

    #Граничные условия
    main_diag_A[0] = 1
    upper_diag_A[0] = 0
    lower_diag_A[0] = 0
    main_diag_A[-1] = 1
    lower_diag_A[-1] = 0
    upper_diag_A[-1] = 0

    main_diag_B[0] = 1
    upper_diag_B[0] = 0
    lower_diag_B[0] = 0
    main_diag_B[-1] = 1
    lower_diag_B[-1] = 0
    upper_diag_B[-1] = 0

    #Создание матриц
    A = diags([lower_diag_A, main_diag_A, upper_diag_A], [-1, 0, 1], format='csr')
    B = diags([lower_diag_B, main_diag_B, upper_diag_B], [-1, 0, 1], format='csr')

    # Обратный ход с проверкой возможности досрочного исполнения
    for n in range(N, 0, -1):
        rhs = B.dot(V[:, n])

        t_prev = (n-1) * dt
        rhs[0] = K * np.exp(-r * (T - t_prev))
        rhs[-1] = 0

        V_next = spsolve(A, rhs)

        #Проверка условия досрочного исполнения
        payoff = payoff_put(S, K)
        V[:, n-1] = np.maximum(V_next, payoff)

    time_grid = np.linspace(0, T, N+1)

    # Проверка: американский опцион должен быть дороже европейского
    eu_price = black_scholes_put(100, K, T, r, sigma)
    am_price = np.interp(100, S, V[:, 0])
    print(f"Проверка американского опциона: EU: {eu_price:.4f}, AM: {am_price:.4f}, "
          f"Премия: {am_price-eu_price:.6f}")

    return S, V, time_grid

#Нахождение границы экспирации
def find_exercise_boundary(S, V, time_grid, K):
    payoff = payoff_put(S, K)
    B = np.zeros(len(time_grid))

    for n in range(len(time_grid)):
        #разница между ценой и выплатой
        diff = V[:, n] - payoff

        #переход от exercise к hold
        positive_indices = np.where(diff > 1e-6)[0]

        if len(positive_indices) > 0:
            first_positive = positive_indices[0]
            if first_positive > 0:
                idx1 = first_positive - 1
                idx2 = first_positive

                S1, S2 = S[idx1], S[idx2]
                d1, d2 = diff[idx1], diff[idx2]

                if d2 - d1 != 0:
                    B[n] = S1 - d1 * (S2 - S1) / (d2 - d1)
                else:
                    B[n] = S1
            else:
                B[n] = S[0]
        else:
            B[n] = S[-1]

    if len(B) > 10:
        window = min(21, len(B)//2*2+1)
        B_smooth = savgol_filter(B, window, 3)
        return B_smooth

    return B

#задача №1: явная схема

print("задача №1: явная схема")


S_exp_stable, V_exp_stable, t_exp_stable = explicit_scheme(K, T, r, sigma, S_max, M, N, 'stable')
S_exp_unstable, V_exp_unstable, t_exp_unstable = explicit_scheme(K, T, r, sigma, S_max, M, 50, 'unstable')

#Задача №2: проверка устойчивости
print('\nПроверка устойчивости')

#Аналитическое решение
S_analytic = np.linspace(0.1, S_max, 500)
V_analytic = black_scholes_put(S_analytic, K, T, r, sigma)

plt.figure(figsize=(14, 6))

#момент T
plt.subplot(1, 2, 1)
plt.plot(S_exp_stable, V_exp_stable[:, 0], 'b-', linewidth=2, label='Явная (устойчивая)')
plt.plot(S_exp_unstable, V_exp_unstable[:, 0], 'r--', linewidth=2, label='Явная (неустойчивая)')
plt.plot(S_analytic, V_analytic, 'g-', linewidth=2, label='Аналитическое')
plt.plot(S_analytic, payoff_put(S_analytic, K), 'k:', linewidth=2, label='Payoff')
plt.xlabel('Цена актива S')
plt.ylabel('Цена опциона V')
plt.title('Европейский пут в момент t=0')
plt.legend()
plt.grid(True, alpha=0.3)

#График невязки
plt.subplot(1, 2, 2)
# Интерполяция для сравнения
f_stable = interp1d(S_exp_stable, V_exp_stable[:, 0], bounds_error=False, fill_value='extrapolate')
f_unstable = interp1d(S_exp_unstable, V_exp_unstable[:, 0], bounds_error=False, fill_value='extrapolate')

V_stable_interp = f_stable(S_analytic)
V_unstable_interp = f_unstable(S_analytic)

error_stable = np.abs(V_stable_interp - V_analytic)
error_unstable = np.abs(V_unstable_interp - V_analytic)

plt.plot(S_analytic, error_stable, 'b-', label='Ошибка (устойчивая)')
plt.plot(S_analytic, error_unstable, 'r-', label='Ошибка (неустойчивая)')
plt.xlabel('Цена актива S')
plt.ylabel('Абсолютная ошибка')
plt.title('Ошибки численного решения')
plt.legend()
plt.grid(True, alpha=0.3)
plt.yscale('log')

plt.tight_layout()
plt.show()

#Схема Кранка-Николсон
print("задача №3: Схема Кранка-Николсон")


S_cn, V_cn, t_cn = crank_nicolson_scheme(K, T, r, sigma, S_max, M, N)

#Проверка безусловной устойчивости
print("задача №4: Проверка безусловной устойчивости")

N_values = [50, 100, 200, 500]
errors_cn = []

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(S_analytic, V_analytic, 'k-', linewidth=3, alpha=0.5, label='Аналитическое')

for N_test in N_values:
    S_test, V_test, t_test = crank_nicolson_scheme(K, T, r, sigma, S_max, M, N_test)

    f_test = interp1d(S_test, V_test[:, 0], bounds_error=False, fill_value='extrapolate')
    V_test_interp = f_test(S_analytic)

    error = np.sqrt(np.mean((V_test_interp - V_analytic)**2))
    errors_cn.append(error)

    plt.plot(S_test, V_test[:, 0], '-', linewidth=2, label=f'N={N_test}')

plt.xlabel('Цена актива S')
plt.ylabel('Цена опциона V')
plt.title('Схема Кранка-Николсона: разные шаги')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(N_values, errors_cn, 'bo-', linewidth=2)
plt.xlabel('Количество шагов по времени N')
plt.ylabel('Среднеквадратичная ошибка')
plt.title('Сходимость схемы Кранка-Николсона')
plt.grid(True, alpha=0.3)
plt.xscale('log')
plt.yscale('log')

plt.tight_layout()
plt.show()

print('\nТаким образом из графика видно, что полунеявная схема Кранка-Николсон асболютно устойчива')

#Задача 5: американский пут
print('\nЗадача №5: американский пут')
S_am, V_am, t_am = american_put_scheme(K, T, r, sigma, S_max, M, N)

#Проверка америкснкого пута
print("задача 6: проверка америкснкого пута")

#Европейский путт для сравнения
S_eu, V_eu, t_eu = crank_nicolson_scheme(K, T, r, sigma, S_max, M, N)


V_eu_interp = np.zeros_like(V_am)
for i in range(len(t_am)):
    f_eu = interp1d(S_eu, V_eu[:, i], bounds_error=False, fill_value='extrapolate')
    V_eu_interp[:, i] = f_eu(S_am)

payoff = payoff_put(S_am, K)


payoff_matrix = np.tile(payoff, (V_am.shape[1], 1)).T


#1 V_am >= payoff
min_diff_payoff = np.min(V_am - payoff_matrix)
print(f"1. V_am >= payoff: {min_diff_payoff >= -1e-6}")
print(f"   Минимальная разница: {min_diff_payoff:.2e}")

#2 V_am >= V_eu
min_diff_eu = np.min(V_am - V_eu_interp)
print(f"2. V_am >= V_eu: {min_diff_eu >= -1e-6}")
print(f"   Минимальная разница: {min_diff_eu:.2e}")

#Визуализация
plt.figure(figsize=(12, 5))

#Сравнение с европейским
plt.subplot(1, 2, 1)
time_indices = [0, N//4, N//2, 3*N//4]

for idx in time_indices:
    t_val = t_am[idx]
    plt.plot(S_am, V_am[:, idx], '-', linewidth=2, label=f'Ам. t={t_val:.2f}')
    plt.plot(S_am, V_eu_interp[:, idx], '--', linewidth=2, label=f'Ев. t={t_val:.2f}')

plt.plot(S_am, payoff, 'k:', linewidth=3, label='Payoff')
plt.xlabel('Цена актива S')
plt.ylabel('Цена опциона V')
plt.title('Сравнение американского и европейского')
plt.legend(loc='upper right')
plt.grid(True, alpha=0.3)

#Премия америкснкого пута
plt.subplot(1, 2, 2)
premium = V_am - V_eu_interp

for idx in time_indices:
    t_val = t_am[idx]
    plt.plot(S_am, premium[:, idx], '-', linewidth=2, label=f't={t_val:.2f}')

plt.axhline(y=0, color='k', linestyle=':', alpha=0.5)
plt.xlabel('Цена актива S')
plt.ylabel('Премия (V_am - V_eu)')
plt.title('Премия за возможность досрочного исполнения')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()


#Поиск границы экспирации
print('\nПоиск границы экспирации')
B = find_exercise_boundary(S_am, V_am, t_am, K)

#оценка для бесконечного горизонта
B_inf = K * r / (r + 0.5*sigma**2)

print(f"Теоретическая B(inf) = {B_inf:.4f}")
print(f"Численная B(0) = {B[0]:.4f}")
print(f"B(T) = {B[-1]:.4f} (ожидается K = {K})")

plt.figure(figsize=(14, 10))

# График 1: Граница экспирации
plt.subplot(2, 2, 1)
time_to_expiry = T - t_am

plt.plot(time_to_expiry, B, 'r-', linewidth=3, label='B(tau)')
plt.axhline(y=K, color='k', linestyle='--', linewidth=2, label=f'K={K}')
plt.axhline(y=B_inf, color='b', linestyle=':', linewidth=2, label=f'B(inf)≈{B_inf:.1f}')

plt.fill_between(time_to_expiry, 0, B, alpha=0.2, color='red', label='Exercise')
plt.fill_between(time_to_expiry, B, S_max, alpha=0.2, color='green', label='Hold')

plt.xlabel('Время до экспирации tau = T-t')
plt.ylabel('Граница экспирации B(tau)')
plt.title('Граница экспирации американского пута')
plt.legend(loc='upper left')
plt.grid(True, alpha=0.3)
plt.gca().invert_xaxis()

# График 2: Области исполнения и удержания
plt.subplot(2, 2, 2)

# Создаем маску областей
payoff = payoff_put(S_am, K)

# ИСПРАВЛЕНИЕ: создаем payoff_matrix для сравнения
payoff_matrix = np.tile(payoff, (V_am.shape[1], 1)).T
exercise_mask = np.zeros_like(V_am)
for n in range(len(t_am)):
    exercise_mask[:, n] = (V_am[:, n] - payoff_matrix[:, n]) < 1e-4  # ИСПРАВЛЕНО

# Уменьшаем разрешение
stride = 10
S_plot = S_am[::stride]
t_plot = time_to_expiry[::stride]
mask_plot = exercise_mask[::stride, ::stride]

T_plot, S_mesh = np.meshgrid(t_plot, S_plot)

plt.contourf(T_plot, S_mesh, mask_plot, levels=[0, 0.5, 1],
             colors=['green', 'red'], alpha=0.5)
plt.plot(time_to_expiry, B, 'k-', linewidth=3, label='Exercise boundary')
plt.xlabel('tau = T-t')
plt.ylabel('Цена актива S')
plt.title('Области исполнения и удержания')
plt.legend()
plt.grid(True, alpha=0.3)
plt.gca().invert_xaxis()

# График 3: Цена опциона с границей
plt.subplot(2, 2, 3)

for idx in [0, N//4, N//2, 3*N//4]:
    t_val = t_am[idx]
    τ_val = T - t_val

    plt.plot(S_am, V_am[:, idx], '-', linewidth=2, label=f'τ={τ_val:.2f}')

    # Отмечаем границу
    if B[idx] > 0:
        plt.axvline(x=B[idx], color='r', linestyle='--', alpha=0.5)

plt.plot(S_am, payoff, 'k:', linewidth=3, label='Payoff')
plt.xlabel('Цена актива S')
plt.ylabel('Цена опциона V')
plt.title('Цена опциона с границей исполнения')
plt.legend(loc='upper right')
plt.grid(True, alpha=0.3)

# График 4: Влияние параметров на границу
plt.subplot(2, 2, 4)

# Разные параметры для сравнения
scenarios = [
    {'r': 0.05, 'sigma': 0.2, 'label': f'Базовый, B(inf)={B_inf:.1f}'},
    {'r': 0.10, 'sigma': 0.2, 'label': f'Высокая r, B(inf)={K*0.1/(0.1+0.5*0.2**2):.1f}'},
    {'r': 0.05, 'sigma': 0.4, 'label': f'Высокая σ, B(inf)={K*0.05/(0.05+0.5*0.4**2):.1f}'},
]

for scenario in scenarios:
    r_test = scenario['r']
    sigma_test = scenario['sigma']

    # Быстрый расчет
    S_test, V_test, t_test = american_put_scheme(K, T, r_test, sigma_test, S_max, 100, 200)
    B_test = find_exercise_boundary(S_test, V_test, t_test, K)
    time_to_expiry_test = T - t_test

    plt.plot(time_to_expiry_test, B_test, '-', linewidth=2, label=scenario['label'])

plt.xlabel('tau = T-t')
plt.ylabel('B(τ)')
plt.title('Влияние параметров на границу')
plt.legend(fontsize=9)
plt.grid(True, alpha=0.3)
plt.gca().invert_xaxis()

plt.tight_layout()
plt.show()









