# -*- coding: utf-8 -*-
"""QuantLib_swap_pricing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHztEW3pkbJ-pZvTK_9-Gh5329mzAthJ
"""

import QuantLib as ql
import numpy as np
import matplotlib.pyplot as plt

#Напишем оценку свопа

ql.Settings.instance().evaluationDate = ql.Date(24, 7, 2026)

#Кривая доходности
yts = ql.YieldTermStructureHandle(
    ql.FlatForward(2, ql.TARGET(), 0.05, ql.Actual360())
)

#Инициализация движка
engine = ql.DiscountingSwapEngine(yts)

#Определение графика и индекса
schedule = ql.MakeSchedule(
    ql.Date(24, 1, 2027),
    ql.Date(24, 1, 2028),
    ql.Period('6M')
)
index = ql.Euribor3M(yts)

#Функция для оценки NPV
def swapFairRate(rate):
  fixed_leg = ql.FixedRateLeg(schedule, ql.Actual360(), [100.], [rate])
  floating_leg = ql.IborLeg([100], schedule, index)
  swap = ql.Swap(fixed_leg, floating_leg)
  swap.setPricingEngine(engine)
  return swap.NPV()

solver = ql.Brent()
fairRate = solver.solve(swapFairRate, 1e-6, 0.0, 0.001)

rates = np.linspace(-0.02, 0.1, 100)
npvs = [swapFairRate(rate) for rate in rates]

plt.figure(figsize=(12, 6))
plt.plot(rates, npvs, label = 'NPV rate', linewidth=2)

plt.axvline(fairRate, color='red', linestyle='--', label=f'Fair rate = {fairRate:.6f}')
plt.axhline(0, color='black', linewidth=0.8)

plt.xlabel('Fixed rate')
plt.ylabel('NPV')
plt.title('Зависимость NPV свопа от фиксированной ставки')
plt.legend()
plt.grid(True)
plt.show()

